# -- templates --------------

aliases:
  - &attach_workspace
      attach_workspace:
        at: .

  - &store_deb_artifacts
      store_artifacts:
        path: "*.deb"

  - &store_rpm_artifacts
      store_artifacts:
        path: "*.rpm"

  - &store_test_results
      store_test_results:
        path: tests

  - &store_test_artifacts
      store_artifacts:
        path: tests

  - &install
      run:
        name: Install tarball
        command: python -m pip install --progress-bar=off $(echo requests-ecp-*.tar.*)[test]

  - &debian_configure
      run:
        name: Configure debian
        command: |
          set -x;
          apt-get -yqq update;
          apt-get -yqq install ca-certificates;

  - &debian_build
      run:
        name: Build
        command: |
          set -x;
          apt-get -yqq update;
          apt-get -yqq install \
              dpkg-dev \
              devscripts \
              python${PYTHON_VERSION:0:1}-pip \
          ;
          pushd $(mktemp -d -p .);
          tar -xf ../requests-ecp-*.tar.* --strip-components=1;
          # install build dependencies
          mk-build-deps --tool "apt-get -y" --install --remove;
          # build binary package
          dpkg-buildpackage -us -uc -b;
          popd;
          ls *.deb | xargs -n1 dpkg --info;
          # mv and install
          rm -rf tmp*;

  - &debian_install
      run:
        name: Install
        command: |
          set -x;
          DEB="python${PYTHON_VERSION:0:1}-requests-ecp*.deb";
          grep -q stretch /etc/os-release && BACKPORTS="-t stretch-backports" || true;
          dpkg --install ${DEB} || { \
              apt-get -y -f ${BACKPORTS} install;
              dpkg --install ${DEB};
          };

  - &centos_build
      run:
        name: Build
        command: |
          set -x;
          yum -y -q update;
          yum -y -q install epel-release;
          yum -y -q update;
          yum -y -q install \
              rpm-build \
              yum-utils \
              python-srpm-macros \
              python3-rpm-macros \
              python3-pip \
          ;
          # build src rpm
          SRPM=$(rpmbuild --define "_topdir $(pwd)" -ts ./requests-ecp-*.tar.* | cut -d\  -f2);
          # install build dependencies
          yum-builddep -y -q ${SRPM};
          # build binary rpm(s)
          rpmbuild --define "_rpmdir $(pwd)" --rebuild ${SRPM};
          # install
          mv */*.rpm .;
          for _rpm in *.rpm; do
              echo "-- RPM summary for ${_rpm}";
              echo "- Contents:"
              rpm -qilp ${_rpm};
              echo "- Provides:"
              rpm -qp --provides ${_rpm};
              echo "- Requires:"
              rpm -qp --requires ${_rpm};
          done;

  - &centos_install
      run:
        name: Install
        command: |
          set -x;
          if [[ "${PYTHON_VERSION:0:1}" -eq 3 ]]; then
              PYXY=$(rpm --eval "%{?python3_pkgversion}");
          else
              PYXY="${PYTHON_VERSION:0:1}";
          fi;
          yum -y --nogpgcheck localinstall ./python${PYXY}-requests-ecp*.rpm

  - &debian_install_test_dependencies
      run:
        name: Install test dependencies
        command: |
          set -x;
          PYM="${PYTHON_VERSION:0:1}"
          grep -q stretch /etc/os-release && BACKPORTS="-t stretch-backports" || true;
          apt-get -yqq ${BACKPORTS} install \
              debianutils \
              python${PYM}-pytest \
              python${PYM}-pytest-cov \
              python${PYM}-requests-mock \
          ;

  - &centos_install_test_dependencies
      run:
        name: Install test dependencies
        command: |
          set -x;
          if [[ "${PYTHON_VERSION:0:1}" -eq 3 ]]; then
              PYXY=$(rpm --eval "%{?python3_pkgversion}");
          else
              PYXY="${PYTHON_VERSION:0:1}";
          fi;
          yum -y -q install \
              which \
              python${PYXY}-pytest \
              python${PYXY}-pytest-cov \
              python${PYXY}-requests-mock \
          ;

  - &test
      run:
        name: Test
        command: |
          set -x;
          # run test suite
          mkdir -pv tests;
          pushd tests;
          python${PYTHON_VERSION} -m pytest \
              --cov requests_ecp \
              --junitxml junit.xml \
              ../test_requests_ecp.py \
          ;

  - &coverage_report
      run:
        name: Coverage report
        command: pushd tests && python${PYTHON_VERSION} -m coverage report --show-missing

  - &codecov
      run:
        name: Submit coverage to codecov
        command: |
          set -x;
          # get OS name from CIRCLE_JOB name (ignore if in a python image)
          export IMAGE=$(python${PYTHON_VERSION} -c "print('${CIRCLE_JOB}'.split(':')[-2])")
          if [[ "${IMAGE}" == "python" ]]; then unset IMAGE; fi
          # install codecov
          python${PYTHON_VERSION} -m pip install codecov
          # upload coverage
          python${PYTHON_VERSION} -m codecov --file tests/.coverage --flags $(uname) python${PYTHON_VERSION/./} ${IMAGE}

  - &debian
      steps:
        - checkout
        - *debian_configure
        - *attach_workspace
        - *debian_build
        - *debian_install
        - *debian_install_test_dependencies
        - *test
        - *coverage_report
        - *codecov
        - *store_test_results
        - *store_test_artifacts
        - *store_deb_artifacts

  - &centos
      steps:
        - checkout
        - *attach_workspace
        - *centos_build
        - *centos_install
        - *centos_install_test_dependencies
        - *test
        - *coverage_report
        - *codecov
        - *store_test_results
        - *store_test_artifacts
        - *store_rpm_artifacts

  - &python
      steps:
        - checkout
        - *attach_workspace
        - *install
        - *test
        - *coverage_report
        - *codecov
        - *store_test_results
        - *store_test_artifacts

# -- jobs -------------------

version: 2
jobs:
  sdist:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Build tarball
          command: python setup.py --quiet sdist --dist-dir .
      - persist_to_workspace:
          root: .
          paths:
            - "requests-ecp-*.tar.gz"

  flake8:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            set -ex;
            python -m pip install --progress-bar=off "flake8>=3.7.0";
            mkdir -pv tests;
            python -m flake8 --output-file tests/flake8.txt;
      - run:
          name: Create flake8 report
          when: always
          command: |
            set -ex;
            python -m pip install --progress-bar=off flake8-junit-report;
            python -m junit_conversor tests/flake8.txt tests/junit.xml;
      - *store_test_results
      - *store_test_artifacts

  debian:stretch:3.5:
    <<: *debian
    docker:
      - image: debian:stretch-backports
    environment:
      PYTHON_VERSION: "3.5"

  debian:buster:3.7:
    <<: *debian
    docker:
      - image: debian:buster
    environment:
      PYTHON_VERSION: "3.7"

  debian:bullseye:3.7:
    <<: *debian
    docker:
      - image: debian:bullseye
    environment:
      PYTHON_VERSION: "3.7"

  centos:8:3.6:
    <<: *centos
    docker:
      - image: centos:8
    environment:
      PYTHON_VERSION: "3.6"

  python:3.5:
    <<: *python
    docker:
      - image: python:3.5-buster
    environment:
      PYTHON_VERSION: "3.5"

  python:3.6:
    <<: *python
    docker:
      - image: python:3.6-buster
    environment:
      PYTHON_VERSION: "3.6"

  python:3.7:
    <<: *python
    docker:
      - image: python:3.7-buster
    environment:
      PYTHON_VERSION: "3.7"

  python:3.8:
    <<: *python
    docker:
      - image: python:3.8-buster
    environment:
      PYTHON_VERSION: "3.8"

  sphinx:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install
          command: python -m pip install --progress-bar=off .[docs]
      - run:
          name: Run sphinx-build
          command: pushd docs && python -m sphinx -M html . _build -E -W

# -- workflow ---------------

workflows:
  version: 2
  build_and_test:
    jobs:
      - sdist
      - flake8
      - centos:8:3.6:
          requires:
            - sdist
      - debian:stretch:3.5:
          requires:
            - sdist
      - debian:buster:3.7:
          requires:
            - sdist
      - debian:bullseye:3.7:
          requires:
            - sdist
      - python:3.5:
          requires:
            - sdist
      - python:3.6:
          requires:
            - sdist
      - python:3.7:
          requires:
            - sdist
      - python:3.8:
          requires:
            - sdist
      - sphinx
