name: requests-ecp
channels:
  - conda-forge
dependencies:
  - lxml
  - pip
  - python>=3
  - requests
  - requests-gssapi>=1.2.2
  - requests-mock>=1.5.0
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - sphinx-tabs
  - sphinx-automodapi
