name: requests-ecp
dependencies:
  - lxml
  - pip
  - python>=3
  - requests
  - requests-kerberos>=0.9.0
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - requests-mock>=1.5.0
    - sphinx-automodapi
    - sphinx_tabs
