name: requests-ecp
channels:
  - conda-forge
dependencies:
  - python>=3
  # build
  - pip
  - setuptools
  # install
  - lxml
  - requests
  - requests-gssapi>=1.2.2
  # tests
  - requests-mock>=1.5.0
  # docs
  - sphinx
  - sphinx_rtd_theme
  - sphinx-tabs
  - sphinx-automodapi
