# -----------------------
#
# Test the package documentation
#
# -----------------------

name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sphinx:
    name: Sphinx

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Cache conda packages
      uses: actions/cache@v2
      env:
        # increment to reset cache
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: docs-conda-${{ env.CACHE_NUMBER }}
        restore-keys: docs-conda-

    - name: Configure conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: docs
        channels: conda-forge
        python-version: '3.9'
        # this is needed for caching to work properly:
        use-only-tar-bz2: true

    - name: Conda info
      run: conda info --all

    - name: Install dependencies
      run: conda env update --name docs --quiet --file docs/rtd-environment.yml

    - name: Install requests-ecp
      run: python -m pip install .[docs] --no-build-isolation -vv

    - name: Package list
      run: conda list --name docs

    - name: Build documentation
      run: python -m sphinx -b html -W -v --color docs/ _build/

    - name: Upload documentation build
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: _build
